export const ErrorMessageConst = {
  ACCOUNT_ADDED: 'ACCOUNT_ADDED',
  ACCOUNT_UPDATED: 'ACCOUNT_UPDATED',
  MEMBER_ADDED: 'MEMBER_ADDED',
  SOMETHING_WENT_WRONG: 'SOMETHING_WENT_WRONG',
  DPS_ADDED: 'DPS_ADDED',
  SOMETHING_WENT_WRONG_WHILE_DELETING_ACCOUNT:
    'SOMETHING_WENT_WRONG_WHILE_DELETING_ACCOUNT',
  SOMETHING_WENT_WRONG_WHILE_DELETING_DPS:
    'SOMETHING_WENT_WRONG_WHILE_DELETING_DPS',
  SUCCESSFULLY_TRANSFERED_MONEY: 'SUCCESSFULLY_TRANSFERED_MONEY',
  PAYMENT_SUCCESSFULLY_DONE: 'PAYMENT_SUCCESSFULLY_DONE',
};
