export const ErrorMessageConst = {
  ACCOUNT_ADDED: 'ACCOUNT_ADDED',
  ACCOUNT_UPDATED: 'ACCOUNT_UPDATED',
  MEMBER_ADDED: 'MEMBER_ADDED',
  SOMETHING_WENT_WRONG: 'SOMETHING_WENT_WRONG',
  DPS_ADDED: 'DPS_ADDED',
};
